# Generated by Django 6.0.3 on 2026-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projectcard_live_link_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
