# Generated by Django 6.0.3 on 2026-05-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latest_view',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
