# Generated by Django 6.0.3 on 2026-05-12 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_latest_view_userprofile_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latest_view',
        ),
        migrations.CreateModel(
            name='ProfileVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visitor', models.CharField(blank=True, max_length=50)),
                ('profile_visitor_time', models.DateTimeField(auto_now=True)),
                ('profile_owver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
    ]
