# Generated by Django 6.0.3 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userprofile_latest_view_profilevisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevisitor',
            name='profile_visitor_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
