# Generated by Django 6.0.3 on 2026-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profilevisitor_profile_visitor_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
