# Generated by Django 6.0.3 on 2026-05-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_security_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=60)),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'support_ticket',
            },
        ),
    ]
