# Generated by Django 6.0.3 on 2026-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='mobile',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
