# Generated by Django 6.0.3 on 2026-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_supportticket_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcard',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
