# Generated by Django 6.0.3 on 2026-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_projectcard_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcard',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(default='', upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
